micronaut:
  application:
    name: micronautStarter
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:swagger
        mapping: /swagger-ui/**
  security:
    enabled: true
    interceptUrlMap:
      - pattern : /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
    endpoints:
      login:
        enabled: true
        path: /api/authenticate
      oauth:
        get-allowed: true
        enabled: true
        path: /api/generate-access-token
    token:
      jwt:
        enabled: true
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: "${JWT_GENERATOR_REFRESH_SECRET:eefe82f8-7ca6-11ea-bc55-0242ac130003}"
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:eefe82f8-7ca6-11ea-bc55-0242ac130003}"
    authentication: bearer
---
datasources:
  default:
    url: jdbc:h2:~/micronaut;DB_CLOSE_DELAY=1;
    username: sa
    driver-class-name: org.h2.Driver
---
liquibase:
  datasources:
    default:
      change-log: classpath:liquibase/master.xml
      enabled: true
---
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true